config/routes.rb
Rails.application.routes.draw do
  #Вход и выход из админки
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'main#index' #Главная
  get 'contacts', to: 'contacts#show', as: 'contacts' #Контакты
  get 'results', to: 'results#index', as: 'results' #Результаты поиска
  get 'item/:id', to: 'items#show', as: 'show_item' #Товар
  get 'gallery/:id', to: 'galleries#show', as: 'show_gallery' #Галерея
  get 'catalog', to: 'categories#show', as: 'catalog', defaults: {id: 'catalog'} #Каталог
  get 'discount', to: 'discount#show', as: 'discount' #Дисконт
  get 'catalog/:id', to: 'categories#show',as: 'subs_and_items' #показ подкатегорий
  resources :news_items, only: [:index, :show] #акции
  resources :orders, only: [:create] # создание заказов
  resources :opinions, only: [:index, :create] #отзывы и создание отзывов
  resources :items, only: [] do
    resources :orders, only: [:create]  #создание заказа из товара
  end


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'discount', to: 'discount#index', as: 'discount'
    resources :items
    resources :categories
    resources :news_items
    resources :opinions
    resources :orders
    resources :galleries
    resources :pictures, only: [:destroy,:update,:edit]
    resources :description_pictures, only: [:destroy,:update,:edit]
    resources :decoration_pictures, only: [:destroy,:update,:edit]
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  #Use this for really simple search througth one model
  include PgSearch
  pg_search_scope :search_everywhere, against: [:title]
  belongs_to :category
  belongs_to :preview, class_name: 'Picture'
  has_many :description_pictures
  has_many :decoration_pictures

  #It is help to make nice routes
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  has_many :pictures, as: :imageable, dependent: :destroy
  def slug_candidates
    [
        :title,
        [:title, :category_id]
    ]
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::AdminController
  before_action :set_gallery, only: [:show,:edit,:update,:destroy]

  # GET /items
  # GET /items.json
  def index
    @galleries = Gallery.all.order(updated_at: :desc)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def new
    @gallery = Gallery.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def create
    @gallery = Gallery.create(gallery_params)
    if params[:images]
      #===== The magic is here ;)
      if @gallery.half_wide?
        params[:images].each { |image|
          @gallery.pictures.create(half_wide: true,image: image)
        }
      else
        params[:images].each { |image|
          @gallery.pictures.create(image: image)
        }
      end
    end
    if params[:description_images]
      params[:description_images].each { |image|
        @gallery.description_pictures.create(image: image)
      }
    end
    if params[:decoration_images]
      params[:decoration_images].each { |image|
        @gallery.decoration_pictures.create(image: image)
      }
    end
    if params[:preview]
      if @gallery.half_wide?
        preview = Picture.create(half_wide: true,image: params[:preview])
      else
        preview = Picture.create(image: params[:preview])
      end
      logger.debug "*********** PREVIEW CHECK #{preview.half_wide?}"
      @gallery.preview = preview
      @gallery.save
    end
    record_activity(current_user.name + " создал новую галлерею " + @gallery.title)
    redirect_to admin_galleries_path
  end

  def update
    @gallery.update(gallery_params)
    if params[:images]
      #===== The magic is here ;)
      if @gallery.half_wide?
        params[:images].each { |image|
          @gallery.pictures.create(half_wide: true,image: image)
        }
      else
        params[:images].each { |image|
          @gallery.pictures.create(image: image)
        }
      end
    end
    if params[:description_images]
      params[:description_images].each { |image|
        @gallery.description_pictures.create(image: image)
      }
    end
    if params[:decoration_images]
      params[:decoration_images].each { |image|
        @gallery.decoration_pictures.create(image: image)
      }
    end
    if params[:preview]
      if @gallery.half_wide?
        preview = Picture.create(half_wide: true,image: params[:preview])
      else
        preview = Picture.create(image: params[:preview])
      end
      logger.debug "*********** PREVIEW CHECK #{preview.half_wide?}"
      @gallery.preview = preview
      @gallery.save
    end
    record_activity(current_user.name + " обновил галлерею " + @gallery.title)
    redirect_to admin_gallery_path(@gallery)
  end

  def destroy
    if @gallery.preview && @gallery.preview.image.exists?
      @gallery.preview.destroy
    end
    if @gallery.pictures.size > 0
      @gallery.pictures.each do |picture|
        picture.destroy
      end
    end
    if @gallery.description_pictures.size > 0
      @gallery._description_pictures.each do |picture|
        picture.destroy
      end
    end
    if @gallery.decoration_pictures.size > 0
      @gallery._decoration_pictures.each do |picture|
        picture.destroy
      end
    end
    gallery_title = @gallery.title
    @gallery.destroy
    record_activity(current_user.name + " удалил галлерею " + gallery_title)
    redirect_to admin_galleries_path
  end

  private

  def set_gallery
    @gallery = Gallery.friendly.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:title,
                                    :description,
                                    :category_id,
                                    :meta_title,
                                    :meta_description,
                                    :header,
                                    :wide,
                                    :half_wide,
                                    :visible)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def show
    @gallery = Gallery.friendly.find(params[:id])
    @category = @gallery.category
    set_meta_tags title: @gallery.meta_title,
                  description: @gallery.meta_description
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for ([:admin, gallery]), :html => {multipart: true} do |f| %>

    <!--Видимость-->
    <div class="checkbox">
      <%= f.label :visible do %>
          <%= f.check_box :visible %>
          Видимость
      <% end %>
    </div>

    <!--Ошибки сохранения галлереи-->
    <% if gallery.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

          <ul>
            <% gallery.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Название-->
    <div class="form-group">
      <%= f.label :title, 'Название' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <!--Описание-->
    <div class="form-group">
      <%= f.label :description, 'Описание' %>
      <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>
      <%= tinymce %>
    </div>

    <!--Изображения для цен-->
    <div class="form-group">
      <%= f.label 'Изображения для цен' %>
      <div class="row">
        <div class="col-md-12">
          Всего изображений: <%= gallery.description_pictures.size %>
        </div>
      </div>
      <div class="row">
        <% gallery.description_pictures.each do |picture| %>
            <div class="col-md-2">
              <div class="image-wrapper">
                <%= link_to admin_description_picture_path(picture), method: :delete, :remote => true, :class => 'delete-image' do %>
                    <div class="image-hover">
                      <div class="image-hover-content">
                        <%= icon ('times') %>
                      </div>
                    </div>
                    <div class="image-container">
                      <div class="image">
                        <%= image_tag picture.image(:for_grid), class: 'img-responsive' %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
      <%= file_field_tag "description_images[]", type: :file, multiple: true %>
    </div>

    <!--Изображения для декоров-->
    <div class="form-group">
      <%= f.label :pictures, 'Изображения для декоров' %>
      <div class="row">
        <div class="col-md-12">
          Всего изображений: <%= gallery.decoration_pictures.size %>
        </div>
      </div>
      <div class="row">
        <% gallery.decoration_pictures.each do |picture| %>
            <div class="col-md-2">
              <div class="image-wrapper">
                <%= link_to admin_decoration_picture_path(picture), method: :delete, :remote => true, :class => 'delete-image' do %>
                    <div class="image-hover">
                      <div class="image-hover-content">
                        <%= icon ('times') %>
                      </div>
                    </div>
                    <div class="image-container">
                      <div class="image">
                        <%= image_tag picture.image(:for_grid), class: 'img-responsive' %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
      <%= file_field_tag "decoration_images[]", type: :file, multiple: true %>
    </div>

    <!--Заголовок галлереи-->
    <div class="form-group">
      <%= f.label :header, 'Заголовок H1' %>
      <%= f.text_field :header, class: 'form-control' %>
    </div>

    <!--Категория-родитель-->
    <div class="form-group">
      <%= f.label :category_id, 'Категория' %>
      <%= f.collection_select :category_id, @categories.order(:id), :id, :title, class: 'form-control' %>
    </div>

    <!--Мета название-->
    <div class="form-group">
      <%= f.label :meta_title, 'Мета-название' %>
      <%= f.text_field :meta_title, class: 'form-control' %>
    </div>

    <!--Мета описание-->
    <div class="form-group">
      <%= f.label :meta_description, 'Мета-описание' %>
      <%= f.text_area :meta_description, class: 'form-control' %>
    </div>

    <!--Изображение превью-->
    <div class="form-group">
      <%= f.label :preview, 'Изображение-превью' %>
      <% if gallery.preview %>
          <div class="row">
            <div class="col-md-3">
              <div class="image-wrapper">
                <%= link_to admin_picture_path(gallery.preview), method: :delete, :remote => true, :class => 'delete-image' do %>
                    <div class="image-hover">
                      <div class="image-hover-content">
                        <%= icon ('times') %>
                      </div>
                    </div>
                    <div class="image-container">
                      <div class="image">
                        <%= image_tag gallery.preview.image(:for_grid), class: 'img-responsive' %>

                      </div>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
      <%= file_field_tag "preview", class: 'form-control' %>
    </div>

    <!--Будет ли во всю страницу превью?-->
    <div class="checkbox">
      <label>
        <%= f.check_box :wide %> Широкое превью
      </label>
    </div>

    <!--Будет ли превью в половину страницы?-->
    <div class="checkbox">
      <label>
        <%= f.check_box :half_wide %> Полуширокое превью
      </label>
    </div>

    <!--Изображения галлереи-->
    <div class="form-group">
      <%= f.label :pictures, 'Изображения' %>
      <div class="row">
        <div class="col-md-12">
          Всего изображений: <%= gallery.pictures.size %>
        </div>
      </div>
      <div class="row">
        <% gallery.pictures.each do |picture| %>
            <div class="col-md-2">
              <div class="image-wrapper">
                <%= link_to admin_picture_path(picture), method: :delete, :remote => true, :class => 'delete-image' do %>
                    <div class="image-hover">
                      <div class="image-hover-content">
                        <%= icon ('times') %>
                      </div>
                    </div>
                    <div class="image-container">
                      <div class="image">
                        <%= image_tag picture.image(:for_grid), class: 'img-responsive' %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>

    <!--Кнопки-->
    <div class="row">
      <%= f.submit 'Сохранить изменения', class: 'btn btn-default' %>
      <%= link_to 'Назад', admin_galleries_path, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/admin/galleries/_tinymce_init.html.erb
<script>

    tinymce.init({
        selector: '#gallery_description',
        plugins: 'image link lists print ' +
        'preview searchreplace visualblocks ' +
        'fullscreen insertdatetime media ' +
        'table contextmenu paste code',
        toolbar: 'bold italic | undo redo | ' +
        'alignleft aligncenter alignright alignjustify | ' +
        'bullist numlist outdent indent | paste | image | link | images_tag | decoration_tag',
        setup: function(editor) {
            editor.addButton('images_tag', {
                text: "Изображения-цены",
                onclick: function () {
                    alert(editor.selection.getContent());
                    editor.insertContent('<div id="price_images" style="color:green">Цены</div>');
                }
            });
            editor.addButton('decoration_tag', {
                text: "Изображения-декоры",
                onclick: function () {
                    alert(editor.selection.getContent());
                    editor.insertContent('<div id="decoration_images" style="color:#00806f">Декоры</div>');
                }
            });
        }
    });
</script>

app/views/admin/galleries/edit.html.erb
<div class="container">

  <!--Инициализация текстового редактора-->
  <%= render 'tinymce_init' %>

  <!--Заголовок страницы-->
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Редактировать галерею</h1>
    </div>
  </div>

  <!--Обертка формы-->
  <div class="row">
    <div class="col-md-12">
      <!--Форма-->
      <%= render 'form', gallery: @gallery%>
    </div>
  </div>

</div>

app/views/admin/galleries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Галереи</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active">
          <%= link_to admin_galleries_path do %>
              <%=icon('list')%>
              Список
          <%end%>
        </li>
        <li role="presentation">
          <%= link_to new_admin_gallery_path do %>
              <%=icon('plus')%>
              Создать
          <%end%>
        </li>
      </ul>
    </div>
    <div class="col-md-12">
      <table class="table table-striped table-hover">
        <caption>Галереи</caption>
        <thead>
        <tr>
          <th>ID</th>
          <th>Название</th>
          <th>Описание</th>
          <th>Категория</th>
          <th>Изображений</th>
          <th>Превью</th>
          <th><abbr title="Заполнен заголовок(SEO)">T</abbr></th>
          <th><abbr title="Заполнено описание(SEO)">D</abbr></th>
          <th><abbr title="Заполнен тег h1">H1</abbr></th>
          <th><abbr title="Альтернативный текст для обложки">PA</abbr></th>
          <th><abbr title="Заполнено описание">Оп</abbr></th>
          <th>Обновлён</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%if @galleries%>
            <%@galleries.each do |gallery|%>
                <tr>
                <%if !gallery.visible?%>
                <tr class="hidden-gallery">
                <%else%>
                <tr>
                <%end%>
                  <th><%= gallery.id %></th>
                  <td><%= gallery.title %></td>
                  <td><%= gallery.description %></td>
                  <td><%= Category.find(gallery.category).title %></td>
                  <td><%= gallery.pictures.size %></td>
                  <td>
                    <%if gallery.preview%>
                        <%=image_tag gallery.preview.image(:thumb), class: 'img-responsive'%>
                    <%else%>
                        Отсутствует
                    <%end%>
                  </td>
                  <td>
                    <%if gallery.meta_title && gallery.meta_title != ''%>
                        <attr title="<%=gallery.meta_title%>"><%= icon('check', class: 'check-icon')%></attr>
                    <%else%>
                        <attr title="Title отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                    <%end%>
                  </td> <!--Заполнен заголовок(SEO)-->
                  <td>
                    <%if gallery.meta_description && gallery.meta_description != ''%>
                        <attr title="<%=gallery.meta_description%>"><%= icon('check', class: 'check-icon')%></attr>
                    <%else%>
                        <attr title="Description отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                    <%end%>
                  </td> <!--Заполнено описание(SEO)-->
                  <td>
                    <%if gallery.header && gallery.header != ''%>
                        <attr title="<%=gallery.header%>"><%= icon('check', class: 'check-icon')%></attr>
                    <%else%>
                        <attr title="Тег H1 отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                    <%end%>
                  </td> <!--Заполнен тег h1-->
                  <td>
                    <%if gallery.preview && gallery.preview.alt && gallery.preview.alt != '' %>
                        <attr title="<%=gallery.preview.alt%>"><%= icon('check', class: 'check-icon')%></attr>
                    <%else%>
                        <attr title="Альтернативный текст для обложки отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                    <%end%>
                  </td> <!--Альтернативный текст для обложки-->
                  <td>
                    <%if gallery.description && gallery.description != ''%>
                        <attr title="<%=gallery.description%>"><%= icon('check', class: 'check-icon')%></attr>
                    <%else%>
                        <attr title="Описание отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                    <%end%>
                  </td> <!--Заполнено описание-->
                  <td><%= time_tag gallery.updated_at %></td>
                  <td>
                    <ul class="controls">
                      <li title="Показать">
                        <%= link_to admin_gallery_path(gallery) do %>
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <%end%>
                      </li>
                      <li title="Редактировать">
                        <%= link_to edit_admin_gallery_path(gallery), class: 'alo' do %>
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        <%end%>
                      </li>
                      <li title="Удалить">
                        <%= link_to admin_gallery_path(gallery), method: :delete, data: { confirm: 'Вы уверены?' } do%>
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <%end%>
                      </li>
                      <li title="Открыть на сайте">
                        <%= link_to show_gallery_path(gallery), class: 'alo' do %>
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        <%end%>
                      </li>
                    </ul>
                  </td>
                </tr>
            <%end%>
        <%else%>
            <tr>
              <th>-</th>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/galleries/new.html.erb
<div class="container">

  <!--Инициализация текстового редактора-->
  <%= render 'tinymce_init' %>

  <!--Заголовок-->
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Создать галерею</h1>
    </div>
  </div>

  <!--Обертка формы-->
  <div class="row">
    <div class="col-md-12">
      <!--Форма-->
      <%= render 'form', gallery: @gallery %>
    </div>
  </div>

</div>

app/views/admin/galleries/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Галерея "<%= @gallery.title %>"</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 panels">
      <div class="panel panel-info">
        <div class="panel-heading">Название</div>
        <div class="panel-body"><%= @gallery.title %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Видимость</div>
        <div class="panel-body">
          <% if @gallery.visible? %>
              Видима
          <% else %>
              Скрыта
          <% end %>
        </div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Описание</div>
        <div class="panel-body"><%= @gallery.description %></div>
      </div>

      <!--Изображения цен-->
      <div class="panel panel-info" id="price-image-panel">
        <div class="panel-heading">Изображения цен | Всего изображений: <%= @gallery.description_pictures.size %></div>
        <div class="panel-body">
          <div class="row">
            <% @gallery.description_pictures.each do |picture| %>
                <div class="col-md-3">
                  <div class="image-wrapper">
                    <%= image_tag picture.image(:for_grid), alt: picture.alt, class: 'img-responsive' %>

                    <%= form_tag "/admin/description_pictures/#{picture.id}", method: 'put', remote: true, class: 'form-inline' do %>
                        <div class="form-group">
                          <%= text_field_tag :alt, picture.alt, placeholder: 'Alt', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-alt"><%= icon 'check' %></button>
                        </div>
                        <div class="form-group">
                          <%= text_field_tag :caption, picture.caption, placeholder: 'Caption', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-caption"><%= icon 'check' %></button>
                        </div>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <!--Изображения декоров-->
      <div class="panel panel-info" id="price-image-panel">
        <div class="panel-heading">Изображения декоров | Всего изображений: <%= @gallery.decoration_pictures.size %></div>
        <div class="panel-body">
          <div class="row">
            <% @gallery.decoration_pictures.each do |picture| %>
                <div class="col-md-3">
                  <div class="image-wrapper">
                    <%= image_tag picture.image(:for_grid), alt: picture.alt, class: 'img-responsive' %>

                    <%= form_tag "/admin/decoration_pictures/#{picture.id}", method: 'put', remote: true, class: 'form-inline' do %>
                        <div class="form-group">
                          <%= text_field_tag :alt, picture.alt, placeholder: 'Alt', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-alt"><%= icon 'check' %></button>
                        </div>
                        <div class="form-group">
                          <%= text_field_tag :caption, picture.caption, placeholder: 'Caption', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-caption"><%= icon 'check' %></button>
                        </div>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Заголовок H1</div>
        <div class="panel-body"><%= @gallery.header %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Категория</div>
        <div class="panel-body"><%= Category.find(@gallery.category).title %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Изображение-превью</div>
        <div class="panel-body">
          <% if @gallery.preview %>
              <%= image_tag @gallery.preview.image(:for_grid), alt: @gallery.preview.alt, class: 'img-responsive' %>
              <%= form_tag "/admin/pictures/#{@gallery.preview.id}", method: 'put', remote: true, class: 'form-inline' do %>
                  <div class="form-group">
                    <%= text_field_tag :alt, @gallery.preview.alt, class: 'form-control' %>
                    <button type="submit" class="btn btn-default change-alt"><%= icon 'check' %></button>
                  </div>
              <% end %>
          <% else %>
              Отсутствует
          <% end %>
        </div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Создано</div>
        <div class="panel-body"><%= time_tag @gallery.created_at %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Обновлено</div>
        <div class="panel-body"><%= time_tag @gallery.updated_at %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Мета-название</div>
        <div class="panel-body"><%= @gallery.meta_title %></div>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">Мета-описание</div>
        <div class="panel-body"><%= @gallery.meta_description %></div>
      </div>
      <div class="panel panel-info" id="image-panel">
        <div class="panel-heading">Изображения | Всего изображений: <%= @gallery.pictures.size %></div>
        <div class="panel-body">
          <div class="row">
            <% @gallery.pictures.each do |picture| %>
                <div class="col-md-3">
                  <div class="image-wrapper">
                    <%= image_tag picture.image(:for_grid), alt: picture.alt, class: 'img-responsive' %>

                    <%= form_tag "/admin/pictures/#{picture.id}", method: 'put', remote: true, class: 'form-inline' do %>
                        <div class="form-group">
                          <%= text_field_tag :alt, picture.alt, placeholder: 'Alt', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-alt"><%= icon 'check' %></button>
                        </div>
                        <div class="form-group">
                          <%= text_field_tag :caption, picture.caption, placeholder: 'Caption', class: 'form-control' %>
                          <button type="submit" class="btn btn-default change-caption"><%= icon 'check' %></button>
                        </div>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 buttons">
      <%= link_to 'Назад', admin_galleries_path, class: 'btn btn-default' %>
      <%= link_to 'Редактировать', edit_admin_gallery_path(@gallery), class: 'btn btn-default' %>
      <%= link_to 'Удалить', admin_gallery_path(@gallery), method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-default' %>
    </div>
  </div>
</div>