config/routes.rb
Rails.application.routes.draw do
  #Вход и выход из админки
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'main#index' #Главная
  get 'contacts', to: 'contacts#show', as: 'contacts' #Контакты
  get 'results', to: 'results#index', as: 'results' #Результаты поиска
  get 'item/:id', to: 'items#show', as: 'show_item' #Товар
  get 'gallery/:id', to: 'galleries#show', as: 'show_gallery' #Галерея
  get 'catalog', to: 'categories#show', as: 'catalog', defaults: {id: 'catalog'} #Каталог
  get 'discount', to: 'discount#show', as: 'discount' #Дисконт
  get 'catalog/:id', to: 'categories#show',as: 'subs_and_items' #показ подкатегорий
  resources :news_items, only: [:index, :show] #акции
  resources :orders, only: [:create] # создание заказов
  resources :opinions, only: [:index, :create] #отзывы и создание отзывов
  resources :items, only: [] do
    resources :orders, only: [:create]  #создание заказа из товара
  end


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'discount', to: 'discount#index', as: 'discount'
    resources :items
    resources :categories
    resources :news_items
    resources :opinions
    resources :orders
    resources :galleries
    resources :pictures, only: [:destroy,:update,:edit]
    resources :description_pictures, only: [:destroy,:update,:edit]
    resources :decoration_pictures, only: [:destroy,:update,:edit]
  end
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :parent, class_name: "Category"
  has_many :subs, :foreign_key => "parent_id", class_name: "Category"
  has_many :items
  has_many :galleries
  belongs_to :preview, class_name: 'Picture'
end

app/models/finished_order.rb
class FinishedOrder < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  #Use this for really simple search througth one model
  include PgSearch
  pg_search_scope :search_everywhere, against: [:title]
  belongs_to :category
  belongs_to :preview, class_name: 'Picture'
  has_many :description_pictures
  has_many :decoration_pictures

  #It is help to make nice routes
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  has_many :pictures, as: :imageable, dependent: :destroy
  def slug_candidates
    [
        :title,
        [:title, :category_id]
    ]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  #Use this for really simple search througth one model
  include PgSearch
  pg_search_scope :search_everywhere, against: [:title, :description]

  #It is help to make nice routes
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :category
  belongs_to :preview, class_name: 'Picture'
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  has_attached_file :image, styles: { show:"1000x1000>",large: "400x400#",medium: "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, presence: true
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy

  validates :name, presence: true, format: {with: /\A[а-яА-ЯЁё]{3,15}\Z/,
                                            message:'Only Cyrillic, in range beetween 3..15'}
  validates :text, presence: true, length: {in: 10..500}

  validates :vk, format: {with: /\A((https:\/\/vk\.com\/id[\d]+)|(https:\/\/vk\.com\/[a-zA-Z\d_]+)|)\Z/}

  validates :ok, format: {with: /\A((https:\/\/ok\.ru\/profile\/[\d]+)|(https:\/\/ok\.ru\/[a-zA-z\d\.]{5,})|)\Z/}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, format: {with: /\A[а-яА-ЯЁё]{2,15}\Z/}
  validates :phone_number, presence: true, format: {with: /\A((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}\Z/}
  validates :email, presence: true
  validates :city, allow_blank: true, format: {with: /\A[а-яА-ЯЁё]{2,20}\Z/}
  validates :order_text,length: {in: 0..500}
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one :item
  has_one :category
  has_one :gallery
  has_attached_file :image, styles:
                    lambda { |attachment|
                      { for_show: "800x800#",
                        for_grid: "500x500#",
                        thumb: "150x150#",
                        half_wide: attachment.instance.half_wide?  ? "600x200#" : "0x0#" }
                    }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
=begin
{for_show: "800x800#",for_grid: "500x500#", thumb: "150x150#" },
=end

#TODO Убрать сжатие

app/models/pictures_group.rb
class PicturesGroup < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :gallery
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable,:timeoutable
end

app/controllers/admin/discount_controller.rb
class Admin::DiscountController < Admin::AdminController
  def index
    @galleries = Gallery.all.where(category: Category.find_by(title: 'discount')).order(updated_at: :desc)
  end
end

app/controllers/discount_controller.rb
class DiscountController < ApplicationController
  def show
    @discount = Category.find_by(title: 'discount')
    @categories = @discount.subs
    @items = @discount.items
    @galleries = @discount.galleries

    set_meta_tags title: @discount.meta_title,
                  description: @discount.meta_description
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/admin/discount/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Дисконтные товары</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active">
          <%= link_to admin_galleries_path do %>
              <%=icon('list')%>
              Список
          <%end%>
        </li>
        <li role="presentation">
          <%= link_to new_admin_gallery_path do %>
              <%=icon('plus')%>
              Создать
          <%end%>
        </li>
      </ul>
    </div>
    <div class="col-md-12">
      <table class="table table-striped table-hover">
        <caption>Дисконтные товары</caption>
        <thead>
        <tr>
          <th>ID</th>
          <th>Название</th>
          <th>Описание</th>
          <th>Категория</th>
          <th>Изображений</th>
          <th>Превью</th>
          <th><abbr title="Заполнен заголовок(SEO)">T</abbr></th>
          <th><abbr title="Заполнено описание(SEO)">D</abbr></th>
          <th><abbr title="Заполнен тег h1">H1</abbr></th>
          <th><abbr title="Альтернативный текст для обложки">PA</abbr></th>
          <th><abbr title="Заполнено описание">Оп</abbr></th>
          <th>Обновлён</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%if @galleries%>
            <%@galleries.each do |gallery|%>
                <tr>
                  <%if !gallery.visible?%>
                    <tr class="hidden-gallery">
                <%else%>
                    <tr>
                <%end%>
                <th><%= gallery.id %></th>
                <td><%= gallery.title %></td>
                <td><%= gallery.description %></td>
                <td><%= Category.find(gallery.category).title %></td>
                <td><%= gallery.pictures.size %></td>
                <td>
                  <%if gallery.preview%>
                      <%=image_tag gallery.preview.image(:thumb), class: 'img-responsive'%>
                  <%else%>
                      Отсутствует
                  <%end%>
                </td>
                <td>
                  <%if gallery.meta_title && gallery.meta_title != ''%>
                      <attr title="<%=gallery.meta_title%>"><%= icon('check', class: 'check-icon')%></attr>
                  <%else%>
                      <attr title="Title отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                  <%end%>
                </td> <!--Заполнен заголовок(SEO)-->
                <td>
                  <%if gallery.meta_description && gallery.meta_description != ''%>
                      <attr title="<%=gallery.meta_description%>"><%= icon('check', class: 'check-icon')%></attr>
                  <%else%>
                      <attr title="Description отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                  <%end%>
                </td> <!--Заполнено описание(SEO)-->
                <td>
                  <%if gallery.header && gallery.header != ''%>
                      <attr title="<%=gallery.header%>"><%= icon('check', class: 'check-icon')%></attr>
                  <%else%>
                      <attr title="Тег H1 отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                  <%end%>
                </td> <!--Заполнен тег h1-->
                <td>
                  <%if gallery.preview && gallery.preview.alt && gallery.preview.alt != '' %>
                      <attr title="<%=gallery.preview.alt%>"><%= icon('check', class: 'check-icon')%></attr>
                  <%else%>
                      <attr title="Альтернативный текст для обложки отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                  <%end%>
                </td> <!--Альтернативный текст для обложки-->
                <td>
                  <%if gallery.description && gallery.description != ''%>
                      <attr title="<%=gallery.description%>"><%= icon('check', class: 'check-icon')%></attr>
                  <%else%>
                      <attr title="Описание отсутствует"><%= icon('times', class: 'times-icon')%></attr>
                  <%end%>
                </td> <!--Заполнено описание-->
                <td><%= time_tag gallery.updated_at %></td>
                <td>
                  <ul class="controls">
                    <li title="Показать">
                      <%= link_to admin_gallery_path(gallery) do %>
                          <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                      <%end%>
                    </li>
                    <li title="Редактировать">
                      <%= link_to edit_admin_gallery_path(gallery), class: 'alo' do %>
                          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                      <%end%>
                    </li>
                    <li title="Удалить">
                      <%= link_to admin_gallery_path(gallery), method: :delete, data: { confirm: 'Вы уверены?' } do%>
                          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                      <%end%>
                    </li>
                    <li title="Открыть на сайте">
                      <%= link_to show_gallery_path(gallery), class: 'alo', target: :_blank do %>
                          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                      <%end%>
                    </li>
                  </ul>
                </td>
                </tr>
            <%end%>
        <%else%>
            <tr>
              <th>-</th>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>