config/routes.rb
Rails.application.routes.draw do
  #Вход и выход из админки
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'main#index' #Главная
  get 'contacts', to: 'contacts#show', as: 'contacts' #Контакты
  get 'results', to: 'results#index', as: 'results' #Результаты поиска
  get 'item/:id', to: 'items#show', as: 'show_item' #Товар
  get 'gallery/:id', to: 'galleries#show', as: 'show_gallery' #Галерея
  get 'catalog', to: 'categories#show', as: 'catalog', defaults: {id: 'catalog'} #Каталог
  get 'discount', to: 'discount#show', as: 'discount' #Дисконт
  get 'catalog/:id', to: 'categories#show',as: 'subs_and_items' #показ подкатегорий
  resources :news_items, only: [:index, :show] #акции
  resources :orders, only: [:create] # создание заказов
  resources :opinions, only: [:index, :create] #отзывы и создание отзывов
  resources :items, only: [] do
    resources :orders, only: [:create]  #создание заказа из товара
  end


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'discount', to: 'discount#index', as: 'discount'
    resources :items
    resources :categories
    resources :news_items
    resources :opinions
    resources :orders
    resources :galleries
    resources :pictures, only: [:destroy,:update,:edit]
    resources :description_pictures, only: [:destroy,:update,:edit]
    resources :decoration_pictures, only: [:destroy,:update,:edit]
  end
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :parent, class_name: "Category"
  has_many :subs, :foreign_key => "parent_id", class_name: "Category"
  has_many :items
  has_many :galleries
  belongs_to :preview, class_name: 'Picture'
end

app/models/finished_order.rb
class FinishedOrder < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  #Use this for really simple search througth one model
  include PgSearch
  pg_search_scope :search_everywhere, against: [:title]
  belongs_to :category
  belongs_to :preview, class_name: 'Picture'
  has_many :description_pictures
  has_many :decoration_pictures

  #It is help to make nice routes
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  has_many :pictures, as: :imageable, dependent: :destroy
  def slug_candidates
    [
        :title,
        [:title, :category_id]
    ]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  #Use this for really simple search througth one model
  include PgSearch
  pg_search_scope :search_everywhere, against: [:title, :description]

  #It is help to make nice routes
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :category
  belongs_to :preview, class_name: 'Picture'
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  has_attached_file :image, styles: { show:"1000x1000>",large: "400x400#",medium: "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, presence: true
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy

  validates :name, presence: true, format: {with: /\A[а-яА-ЯЁё]{3,15}\Z/,
                                            message:'Only Cyrillic, in range beetween 3..15'}
  validates :text, presence: true, length: {in: 10..500}

  validates :vk, format: {with: /\A((https:\/\/vk\.com\/id[\d]+)|(https:\/\/vk\.com\/[a-zA-Z\d_]+)|)\Z/}

  validates :ok, format: {with: /\A((https:\/\/ok\.ru\/profile\/[\d]+)|(https:\/\/ok\.ru\/[a-zA-z\d\.]{5,})|)\Z/}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, format: {with: /\A[а-яА-ЯЁё]{2,15}\Z/}
  validates :phone_number, presence: true, format: {with: /\A((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}\Z/}
  validates :email, presence: true
  validates :city, allow_blank: true, format: {with: /\A[а-яА-ЯЁё]{2,20}\Z/}
  validates :order_text,length: {in: 0..500}
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one :item
  has_one :category
  has_one :gallery
  has_attached_file :image, styles:
                    lambda { |attachment|
                      { for_show: "800x800#",
                        for_grid: "500x500#",
                        thumb: "150x150#",
                        half_wide: attachment.instance.half_wide?  ? "600x200#" : "0x0#" }
                    }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
=begin
{for_show: "800x800#",for_grid: "500x500#", thumb: "150x150#" },
=end

#TODO Убрать сжатие

app/models/pictures_group.rb
class PicturesGroup < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :gallery
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable,:timeoutable
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
  def index
    @discounts_size = Category.find_by(title: 'discount').galleries.size
    if @discounts_size != 0
      @discounts_last_update = Category.find_by(title: 'discount').galleries.order(updated_at: :desc).first.updated_at
    end

    @galleries_size = Gallery.all.size;
    if @galleries_size != 0
      @galleries_last_update = Gallery.all.order(updated_at: :desc).first.updated_at
    end

    @news_items_size = NewsItem.all.size;
    if @news_items_size != 0
      @news_items_last_update = NewsItem.all.order(updated_at: :desc).first.updated_at
    end

    @opinions_size = Opinion.all.size;
    if @opinions_size != 0
      @opinions_last_update = Opinion.all.order(updated_at: :desc).first.updated_at
    end

    @orders_size = Order.all.size;
    if @orders_size != 0
      @orders_last_update = Order.all.order(updated_at: :desc).first.updated_at
    end

    @categories_size = Category.all.size;
    if @categories_size != 0
      @categories_last_update = Category.all.order(updated_at: :desc).first.updated_at
    end

    @users = User.all

    @activity_logs = ActivityLog.all.order(created_at: :desc)
    @activity_logs_size = ActivityLog.where("created_at >= ?", Time.zone.now.beginning_of_day).size
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/admin/dashboard/_panels.html.erb
<div class="row">
  <!-- Панель с галереями-->
  <div class="col-md-4">
    <%=link_to admin_galleries_path, class:'panel-hover' do%>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="row">
              <div class="col-md-12">
                Последнее изменение:
                <% if @galleries_last_update %>
                    <%= time_tag @galleries_last_update%>
                <%else%>
                    Нет данных
                <%end%>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-3">
                <%=icon('shopping-bag', class: 'fa-5x icon-admin',)%>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%=@galleries_size%></div>
                <div>Галереи</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Работать с галереями</span>
            <span class="pull-right"><%=icon('arrow-circle-right')%></span>
            <div class="clearfix"></div>
          </div>
        </div>
    <%end%>
  </div>

  <!--Панель с категориями-->
  <div class="col-md-4">
    <%=link_to admin_categories_path, class:'panel-hover' do%>
    <div class="panel panel-blue">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            Последнее изменение:
            <% if @categories_last_update %>
                <%= time_tag @categories_last_update%>
            <%else%>
                Нет данных
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3">
            <%=icon('folder-open', class: 'fa-5x icon-admin')%>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%=@categories_size%></div>
            <div>Категории</div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <span class="pull-left">Работать с категориями</span>
        <span class="pull-right"><%=icon('arrow-circle-right')%></span>
        <div class="clearfix"></div>
      </div>
    </div>
    <%end%>
  </div>

  <!--Панель с Дисконтами-->
  <div class="col-md-4">
    <%=link_to admin_discount_path, class:'panel-hover' do%>
        <div class="panel panel-grey">
          <div class="panel-heading">
            <div class="row">
              <div class="col-md-12">
                Последнее изменение:
                <% if @discounts_last_update %>
                    <%= time_tag @discounts_last_update%>
                <%else%>
                    Нет данных
                <%end%>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-3">
                <%=icon('usd', class: 'fa-5x icon-admin',)%>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%=@discounts_size%></div>
                <div>Дисконтные товары</div>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">Работать с дисконтными товарами</span>
            <span class="pull-right"><%=icon('arrow-circle-right')%></span>
            <div class="clearfix"></div>
          </div>
        </div>
    <%end%>
  </div>

  <!--Панель с акциями-->
  <div class="col-md-4">
    <%=link_to admin_news_items_path, class:'panel-hover' do%>
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            Последнее изменение:
            <% if @news_items_last_update %>
                <%= time_tag @news_items_last_update%>
            <%else%>
                Нет данных
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3">
            <%=icon('tags', class: 'fa-5x icon-admin')%>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%=@news_items_size%></div>
            <div>Акции</div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <span class="pull-left">Работать с акциями</span>
        <span class="pull-right"><%=icon('arrow-circle-right')%></span>
        <div class="clearfix"></div>
      </div>
    </div>
    <%end%>
  </div>
  <!--Панель с отзывами-->
  <div class="col-md-4">
    <%=link_to admin_opinions_path, class:'panel-hover' do%>
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            Последнее изменение:
            <% if @opinions_last_update %>
                <%= time_tag @opinions_last_update%>
            <%else%>
                Нет данных
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3">
            <%=icon('comments-o', class: 'fa-5x icon-admin')%>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%=@opinions_size%></div>
            <div>Отзывы</div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <span class="pull-left">Работать с отзывами</span>
        <span class="pull-right"><%=icon('arrow-circle-right')%></span>
        <div class="clearfix"></div>
      </div>
    </div>
    <%end%>
  </div>
  <!--Панель с заказами-->
  <div class="col-md-4">
    <%=link_to admin_orders_path, class:'panel-hover' do%>
    <div class="panel panel-shell">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            Последнее изменение:
            <% if @orders_last_update %>
                <%= time_tag @orders_last_update%>
            <%else%>
                Нет данных
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3">
            <%=icon('cart-plus', class: 'fa-5x icon-admin')%>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%=@orders_size%></div>
            <div>Заказы</div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <span class="pull-left">Работать с заказами</span>
        <span class="pull-right"><%=icon('arrow-circle-right')%></span>
        <div class="clearfix"></div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/admin/dashboard/_tasks.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=icon('check-circle', class: 'fa-2x')%>
        Задачи
      </div>
      <div class="panel-body">
        <ul class="timeline">
          <li>
            <div class="timeline-badge">
              <%=icon('check')%>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Lorem ipsum</h4>
                <p>
                  <small class="text-muted">
                    <%=icon('clock-o')%>
                    12 часов назад
                  </small>
                </p>
              </div>
              <div class="timeline-body">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero
                  laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia
                  pariatur? Est cum veniam excepturi. Maiores praesentium, porro
                  voluptas suscipit facere rem dicta, debitis.
                </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge">
              <%=icon('check')%>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Lorem ipsum</h4>
                <p>
                  <small class="text-muted">
                    <%=icon('clock-o')%>
                    12 часов назад
                  </small>
                </p>
              </div>
              <div class="timeline-body">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero
                  laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia
                  pariatur? Est cum veniam excepturi. Maiores praesentium, porro
                  voluptas suscipit facere rem dicta, debitis.
                </p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge">
              <%=icon('check')%>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Lorem ipsum</h4>
                <p>
                  <small class="text-muted">
                    <%=icon('clock-o')%>
                    12 часов назад
                  </small>
                </p>
              </div>
              <div class="timeline-body">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero
                  laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia
                  pariatur? Est cum veniam excepturi. Maiores praesentium, porro
                  voluptas suscipit facere rem dicta, debitis.
                </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge">
              <%=icon('check')%>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Lorem ipsum</h4>
                <p>
                  <small class="text-muted">
                    <%=icon('clock-o')%>
                    12 часов назад
                  </small>
                </p>
              </div>
              <div class="timeline-body">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero
                  laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia
                  pariatur? Est cum veniam excepturi. Maiores praesentium, porro
                  voluptas suscipit facere rem dicta, debitis.
                </p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge">
              <%=icon('check')%>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Lorem ipsum</h4>
                <p>
                  <small class="text-muted">
                    <%=icon('clock-o')%>
                    12 часов назад
                  </small>
                </p>
              </div>
              <div class="timeline-body">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero
                  laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia
                  pariatur? Est cum veniam excepturi. Maiores praesentium, porro
                  voluptas suscipit facere rem dicta, debitis.
                </p>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/admin/dashboard/_users_list.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <caption>Товары</caption>
      <thead>
      <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Админ</th>
        <th>Входов</th>
        <th>Текущая сессия</th>
        <th>Время сессии</th>
        <th>IP текущей сессии</th>
        <th>Последней сессии</th>
        <th>IP последней сессии</th>
      </tr>
      </thead>
      <tbody>
      <%if @users%>
          <%@users.each do |user|%>
              <tr>
                <th><%= user.id %></th><!--id-->

                <td><%= user.name %></td><!--Имя пользователя-->

                <td>
                  <%if user.admin%>
                      <%= icon('check', class: 'check-icon')%>
                  <%else%>
                      <%= icon('times', class: 'times-icon')%>
                  <%end%>
                </td> <!--Присвоена админка-->

                <td><%= user.sign_in_count %></td> <!--Количество входов-->

                <td>
                  <%if user.current_sign_in_at != nil%>
                    <%= time_tag user.current_sign_in_at %>
                  <%else%>
                    -
                  <%end%>
                </td> <!--Время начала текущей сессии-->

                <td>
                  <%if user.current_sign_in_at != nil%>

                      <%=distance_of_time_in_words(user.current_sign_in_at,DateTime.now)%>
                  <%else%>
                      -
                  <%end%>
                </td> <!--Время текущей сессии-->

                <td>
                  <%if user.current_sign_in_ip != nil%>
                      <%= user.current_sign_in_ip %>
                  <%else%>
                      -
                  <%end%>
                </td> <!--IP текущей сессии-->

                <td>
                  <%if user.last_sign_in_at != nil%>
                      <%= time_tag user.last_sign_in_at %>
                  <%else%>
                      -
                  <%end%>
                </td> <!--Время начала последней сессии-->

                <td>
                  <%if user.last_sign_in_ip != nil%>
                      <%=user.last_sign_in_ip %>
                  <%else%>
                      -
                  <%end%>
                </td> <!--IP последней сессии-->
              </tr>
          <%end%>
      <%else%>
          <tr>
            <th>-</th>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
      <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/dashboard/_users_operations_list.html.erb
<div class="row">
  <div class="col-md-12 inner-table">
    <table class="table table-striped table-hover">
      <caption>Операций за сегодня: <%=@activity_logs_size%></caption>
      <thead>
      <tr>
        <th>Имя</th>
        <th>IP</th>
        <th>Время</th>
        <th>Note</th>
        <th><abbr title="Имя контроллера">C</abbr></th>
        <th><abbr title="Имя экшна">A</abbr></th>
        <th><abbr title="Данные о браузере">B</abbr></th>
        <th><abbr title="Параметры действия">P</abbr></th>
      </tr>
      </thead>
      <tbody>
      <%if @activity_logs%>
          <%@activity_logs.each do |log|%>
              <tr>
                <td><%= log.user.name %></td><!--Имя пользователя-->
                <td><attr title="<%= log.user.current_sign_in_ip %> %>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.created_at %>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.note %>"><%= log.note %></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.controller %>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.action %>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.browser %>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
                <td><attr title="<%= log.params%>"><%= icon('eye')%></attr></td><!--Имя пользователя-->
              </tr>
          <%end%>
      <%else%>
          <tr>
            <th>-</th>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
      <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Панель управления</h1>
    </div>
  </div>
  <%=render 'admin/dashboard/panels'%>
  <% if current_user.admin? %>
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header">Пользователи</h1>
        </div>
      </div>
      <%=render 'admin/dashboard/users_list'%>
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header">Операции пользователей</h1>
        </div>
      </div>
      <%=render 'admin/dashboard/users_operations_list'%>
  <%end%>
</div>