config/routes.rb
Rails.application.routes.draw do
  #Вход и выход из админки
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'main#index' #Главная
  get 'contacts', to: 'contacts#show', as: 'contacts' #Контакты
  get 'results', to: 'results#index', as: 'results' #Результаты поиска
  get 'item/:id', to: 'items#show', as: 'show_item' #Товар
  get 'gallery/:id', to: 'galleries#show', as: 'show_gallery' #Галерея
  get 'catalog', to: 'categories#show', as: 'catalog', defaults: {id: 'catalog'} #Каталог
  get 'discount', to: 'discount#show', as: 'discount' #Дисконт
  get 'catalog/:id', to: 'categories#show',as: 'subs_and_items' #показ подкатегорий
  resources :news_items, only: [:index, :show] #акции
  resources :orders, only: [:create] # создание заказов
  resources :opinions, only: [:index, :create] #отзывы и создание отзывов
  resources :items, only: [] do
    resources :orders, only: [:create]  #создание заказа из товара
  end


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'discount', to: 'discount#index', as: 'discount'
    resources :items
    resources :categories
    resources :news_items
    resources :opinions
    resources :orders
    resources :galleries
    resources :pictures, only: [:destroy,:update,:edit]
    resources :description_pictures, only: [:destroy,:update,:edit]
    resources :decoration_pictures, only: [:destroy,:update,:edit]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :parent, class_name: "Category"
  has_many :subs, :foreign_key => "parent_id", class_name: "Category"
  has_many :items
  has_many :galleries
  belongs_to :preview, class_name: 'Picture'
end

app/controllers/admin/categories_controller.rb
module Admin
class CategoriesController < AdminController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order(updated_at: :desc)
  end

  def show
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def create
    @category = Category.create(category_params)
    if params[:subs][:sub_id]
      params[:subs][:sub_id].delete_at(0)
      params[:subs][:sub_id].each do |sub|
        subcategory = Category.find(sub)
        subcategory.parent_id = @category.id
        subcategory.save
      end
    end
    if params[:preview]
      preview = Picture.create(image: params[:preview])
      @category.preview = preview
      @category.save
    end
    record_activity(current_user.name + " создал новую категорию " + @category.title)
    redirect_to admin_categories_path
  end

  def update
    @category.update(category_params)
    if params[:subs][:sub_id]
      params[:subs][:sub_id].delete_at(0)
      params[:subs][:sub_id].each do |sub|
        subcategory = Category.find(sub)
        subcategory.parent_id = @category.id
        subcategory.save
      end
    end
    if !@category.preview && params[:preview]
      preview = Picture.create(image: params[:preview])
      @category.preview = preview
      @category.save
    end
    record_activity(current_user.name + " обновил категорию " + @category.title)
    redirect_to admin_category_path(@category)
  end


  def destroy
    if (!(@category.title.to_s == 'catalog'.to_s) && !(@category.title.to_s == 'discount'.to_s))
      if @category.preview && @category.preview.image.exists?
        @category.preview.destroy
      end
      category_title = @category.title
      @category.destroy
      record_activity(current_user.name + " удалил категорию " + category_title)
    end
    redirect_to :back
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:description, :parent_id, :title,:meta_title,:meta_description,:header)
  end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.friendly.find(params[:id]);
    @categories = @category.subs
    @items = @category.items
    @galleries = @category.galleries.where(visible: true)
    set_meta_tags title: @category.meta_title,
                  description: @category.meta_description
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="container box">
  <!--Хлебные крошки-->
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-12  breadcrumbs-panel">
        <ol class="breadcrumb">
          <li><%=link_to 'Главная', root_path%></li>
            <%if @category.title == 'catalog'%>
              <li class="active">
              Каталог
              </li>
            <%else%>
              <li>
                <%=link_to 'Каталог', catalog_path%>
              </li>
            <%end%>
          <%if @category.title != 'catalog'%>
          <li class="active">
            <%if @category%>
                <%= @category.title%>
            <%end%>
          </li>
          <%end%>
        </ol>
      </div>
      <%if @category.header && @category.header != ''%>
      <div class="col-md-12">
        <h1 class="main-header"><%=@category.header.html_safe%></h1>
      </div>
      <%end%>
    </div>
  </div>
  <%if @category.description && @category.description != ''%>
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default description-panel">
            <div class="panel-body">
              <%=@category.description.html_safe%>
            </div>
          </div>
        </div>
      </div>
  <%end%>
  <!--Содержание категории-->
  <div class="row">
    <div class="col-md-12">
      <!--Категории-->
      <% if @categories && @categories.size != 0 %>
      <% @categories.each do |category| %>
          <div class="col-md-4 col-sm-6 col-xs-6">
              <%= link_to subs_and_items_path(category) do%>
              <div class="catalog-item-container">
                <%=image_tag category.preview.image(:for_grid), alt: category.preview.alt, class: 'img-responsive'%>
                <div class="item-caption">
                  <%=category.title%>
                </div>
              </div>
              <%end%>
          </div>
      <%end%>
      <% end %>
      <!--Товары-->
      <% if @items && @items.size != 0 %>
      <% @items.each do |item| %>
              <%if !item.wide %>
                <div class="col-md-4 col-sm-6 col-xs-6">
                    <%= link_to show_item_path(item) do%>
                        <div class="catalog-item-container">
                          <%=image_tag item.preview.image(:for_grid), alt: item.preview.alt, class: 'img-responsive' %>
                          <div class="item-caption">
                            <%=item.title%>
                          </div>
                        </div>
                    <%end%>
                </div>
              <%else%>
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <%= link_to show_item_path(item) do%>
                        <div class="catalog-item-container">
                          <%=image_tag item.preview.image, alt: item.preview.alt, class: 'img-responsive' %>
                        </div>
                    <%end%>
                  </div>
              <%end%>
      <%end%>
      <% end %>
      <!--Галлереи-->
      <% if @galleries && @galleries.size != 0 %>
          <% @galleries.each do |gallery| %>
              <%if !gallery.wide && !gallery.half_wide %>
              <div class="col-md-4 col-sm-6 col-xs-6">
                  <%= link_to show_gallery_path(gallery) do%>
                      <div class="catalog-item-container">
                        <%=image_tag gallery.preview.image(:for_grid), alt: gallery.preview.alt, class: 'img-responsive' %>
                        <div class="item-caption">
                          <%=gallery.title%>
                        </div>
                      </div>
                  <%end%>
              </div>
              <%else%>
                  <%if gallery.half_wide%>
                      <div class="col-md-6 col-sm-6 col-xs-6">
                        <%= link_to show_gallery_path(gallery) do%>
                            <div class="catalog-item-container">
                              <%=image_tag gallery.preview.image(:half_wide), alt: gallery.preview.alt, class: 'img-responsive' %>
                              <div class="item-caption">
                                <%=gallery.title%>
                              </div>
                            </div>
                        <%end%>
                      </div>
                  <%else%>
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <%= link_to show_gallery_path(gallery) do%>
                        <div class="catalog-item-container">
                          <%=image_tag gallery.preview.image, alt: gallery.preview.alt, class: 'img-responsive' %>
                        </div>
                    <%end%>
                  </div>
                  <%end%>
              <%end%>
          <%end%>
      <% end %>
    </div>
  </div>
</div>